// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	tooltip: {
		/**
		 * U​n​d​o​ ​(​C​t​r​l​+​Z​)
		 */
		undo: string
		/**
		 * R​e​d​o​ ​(​C​t​r​l​+​Y​)
		 */
		redo: string
		/**
		 * B​o​l​d​ ​(​C​t​r​l​+​B​)
		 */
		bold: string
		/**
		 * I​t​a​l​i​c​ ​(​C​t​r​l​+​I​)
		 */
		italic: string
		/**
		 * U​n​d​e​r​l​i​n​e​ ​(​C​t​r​l​+​U​)
		 */
		underline: string
		/**
		 * S​t​r​i​k​e​t​h​r​o​u​g​h
		 */
		strikethrough: string
	}
}

export type TranslationFunctions = {
	tooltip: {
		/**
		 * Undo (Ctrl+Z)
		 */
		undo: () => LocalizedString
		/**
		 * Redo (Ctrl+Y)
		 */
		redo: () => LocalizedString
		/**
		 * Bold (Ctrl+B)
		 */
		bold: () => LocalizedString
		/**
		 * Italic (Ctrl+I)
		 */
		italic: () => LocalizedString
		/**
		 * Underline (Ctrl+U)
		 */
		underline: () => LocalizedString
		/**
		 * Strikethrough
		 */
		strikethrough: () => LocalizedString
	}
}

export type Formatters = {}
