// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'ko'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	toolbar: {
		/**
		 * U​n​d​o​ ​(​C​t​r​l​+​Z​)
		 */
		undo: string
		/**
		 * R​e​d​o​ ​(​C​t​r​l​+​Y​)
		 */
		redo: string
		/**
		 * S​e​l​e​c​t​ ​a​l​l​ ​(​C​t​r​l​+​A​)
		 */
		selectAll: string
		/**
		 * P​a​r​a​g​r​a​p​h
		 */
		paragraph: string
		/**
		 * B​l​o​c​k​ ​q​u​o​t​a​t​i​o​n
		 */
		blockQuote: string
		/**
		 * N​u​m​b​e​r​e​d​ ​l​i​s​t
		 */
		numberedList: string
		/**
		 * B​u​l​l​e​t​e​d​ ​l​i​s​t
		 */
		bulletedList: string
		/**
		 * C​h​e​c​k​l​i​s​t
		 */
		checklist: string
		/**
		 * A​l​i​g​n​ ​l​e​f​t
		 */
		alignLeft: string
		/**
		 * A​l​i​g​n​ ​c​e​n​t​e​r
		 */
		alignCenter: string
		/**
		 * A​l​i​g​n​ ​r​i​g​h​t
		 */
		alignRight: string
		/**
		 * A​l​i​g​n​ ​j​u​s​t​i​f​y
		 */
		alignJustify: string
		/**
		 * I​n​c​r​e​a​s​e​ ​i​n​d​e​n​t
		 */
		increaseIndent: string
		/**
		 * D​e​c​r​e​a​s​e​ ​i​n​d​e​n​t
		 */
		decreaseIndent: string
		/**
		 * B​o​l​d​ ​(​C​t​r​l​+​B​)
		 */
		bold: string
		/**
		 * I​t​a​l​i​c​ ​(​C​t​r​l​+​I​)
		 */
		italic: string
		/**
		 * U​n​d​e​r​l​i​n​e​ ​(​C​t​r​l​+​U​)
		 */
		underline: string
		/**
		 * S​t​r​i​k​e​t​h​r​o​u​g​h
		 */
		strikethrough: string
		/**
		 * S​u​p​e​r​s​c​r​i​p​t
		 */
		superscript: string
		/**
		 * S​u​b​s​c​r​i​p​t
		 */
		subscript: string
		/**
		 * I​n​l​i​n​e​ ​c​o​d​e
		 */
		code: string
		/**
		 * R​e​m​o​v​e​ ​f​o​r​m​a​t
		 */
		removeFormat: string
		/**
		 * F​o​r​m​a​t​ ​p​a​i​n​t​e​r
		 */
		formatPainter: string
		/**
		 * L​i​n​k
		 */
		link: string
		/**
		 * H​o​r​i​z​o​n​t​a​l​ ​l​i​n​e
		 */
		hr: string
		/**
		 * C​o​d​e​ ​b​l​o​c​k
		 */
		codeBlock: string
		/**
		 * H​e​a​d​i​n​g
		 */
		heading: string
		/**
		 * H​e​a​d​i​n​g​ ​1
		 */
		heading1: string
		/**
		 * H​e​a​d​i​n​g​ ​2
		 */
		heading2: string
		/**
		 * H​e​a​d​i​n​g​ ​3
		 */
		heading3: string
		/**
		 * H​e​a​d​i​n​g​ ​4
		 */
		heading4: string
		/**
		 * H​e​a​d​i​n​g​ ​5
		 */
		heading5: string
		/**
		 * H​e​a​d​i​n​g​ ​6
		 */
		heading6: string
		/**
		 * L​i​s​t
		 */
		list: string
		/**
		 * A​l​i​g​n​m​e​n​t
		 */
		align: string
		/**
		 * I​n​d​e​n​t
		 */
		indent: string
		/**
		 * F​o​n​t​ ​f​a​m​i​l​y
		 */
		fontFamily: string
		/**
		 * F​o​n​t​ ​s​i​z​e
		 */
		fontSize: string
		/**
		 * M​o​r​e​ ​s​t​y​l​e
		 */
		moreStyle: string
		/**
		 * F​o​n​t​ ​c​o​l​o​r
		 */
		fontColor: string
		/**
		 * H​i​g​h​l​i​g​h​t
		 */
		highlight: string
		/**
		 * I​m​a​g​e
		 */
		image: string
		/**
		 * R​e​m​o​v​e​ ​c​o​l​o​r
		 */
		removeColor: string
	}
	link: {
		/**
		 * N​e​w​ ​l​i​n​k
		 */
		newLink: string
		/**
		 * U​R​L
		 */
		url: string
		/**
		 * L​i​n​k​ ​t​i​t​l​e
		 */
		title: string
		/**
		 * C​o​p​y​ ​l​i​n​k​ ​t​o​ ​c​l​i​p​b​o​a​r​d
		 */
		copy: string
		/**
		 * O​p​e​n​ ​l​i​n​k​ ​i​n​ ​n​e​w​ ​t​a​b
		 */
		open: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * R​e​m​o​v​e​ ​l​i​n​k
		 */
		unlink: string
	}
	image: {
		/**
		 * F​u​l​l​ ​s​c​r​e​e​n
		 */
		view: string
		/**
		 * D​e​l​e​t​e
		 */
		remove: string
		/**
		 * P​r​e​v​i​o​u​s
		 */
		previous: string
		/**
		 * N​e​x​t
		 */
		next: string
		/**
		 * C​l​o​s​e​ ​(​E​s​c​)
		 */
		close: string
		/**
		 * T​h​e​ ​i​m​a​g​e​ ​c​a​n​n​o​t​ ​b​e​ ​l​o​a​d​e​d
		 */
		loadingError: string
		/**
		 * Z​o​o​m​ ​o​u​t
		 */
		zoomOut: string
		/**
		 * Z​o​o​m​ ​i​n
		 */
		zoomIn: string
	}
}

export type TranslationFunctions = {
	toolbar: {
		/**
		 * Undo (Ctrl+Z)
		 */
		undo: () => LocalizedString
		/**
		 * Redo (Ctrl+Y)
		 */
		redo: () => LocalizedString
		/**
		 * Select all (Ctrl+A)
		 */
		selectAll: () => LocalizedString
		/**
		 * Paragraph
		 */
		paragraph: () => LocalizedString
		/**
		 * Block quotation
		 */
		blockQuote: () => LocalizedString
		/**
		 * Numbered list
		 */
		numberedList: () => LocalizedString
		/**
		 * Bulleted list
		 */
		bulletedList: () => LocalizedString
		/**
		 * Checklist
		 */
		checklist: () => LocalizedString
		/**
		 * Align left
		 */
		alignLeft: () => LocalizedString
		/**
		 * Align center
		 */
		alignCenter: () => LocalizedString
		/**
		 * Align right
		 */
		alignRight: () => LocalizedString
		/**
		 * Align justify
		 */
		alignJustify: () => LocalizedString
		/**
		 * Increase indent
		 */
		increaseIndent: () => LocalizedString
		/**
		 * Decrease indent
		 */
		decreaseIndent: () => LocalizedString
		/**
		 * Bold (Ctrl+B)
		 */
		bold: () => LocalizedString
		/**
		 * Italic (Ctrl+I)
		 */
		italic: () => LocalizedString
		/**
		 * Underline (Ctrl+U)
		 */
		underline: () => LocalizedString
		/**
		 * Strikethrough
		 */
		strikethrough: () => LocalizedString
		/**
		 * Superscript
		 */
		superscript: () => LocalizedString
		/**
		 * Subscript
		 */
		subscript: () => LocalizedString
		/**
		 * Inline code
		 */
		code: () => LocalizedString
		/**
		 * Remove format
		 */
		removeFormat: () => LocalizedString
		/**
		 * Format painter
		 */
		formatPainter: () => LocalizedString
		/**
		 * Link
		 */
		link: () => LocalizedString
		/**
		 * Horizontal line
		 */
		hr: () => LocalizedString
		/**
		 * Code block
		 */
		codeBlock: () => LocalizedString
		/**
		 * Heading
		 */
		heading: () => LocalizedString
		/**
		 * Heading 1
		 */
		heading1: () => LocalizedString
		/**
		 * Heading 2
		 */
		heading2: () => LocalizedString
		/**
		 * Heading 3
		 */
		heading3: () => LocalizedString
		/**
		 * Heading 4
		 */
		heading4: () => LocalizedString
		/**
		 * Heading 5
		 */
		heading5: () => LocalizedString
		/**
		 * Heading 6
		 */
		heading6: () => LocalizedString
		/**
		 * List
		 */
		list: () => LocalizedString
		/**
		 * Alignment
		 */
		align: () => LocalizedString
		/**
		 * Indent
		 */
		indent: () => LocalizedString
		/**
		 * Font family
		 */
		fontFamily: () => LocalizedString
		/**
		 * Font size
		 */
		fontSize: () => LocalizedString
		/**
		 * More style
		 */
		moreStyle: () => LocalizedString
		/**
		 * Font color
		 */
		fontColor: () => LocalizedString
		/**
		 * Highlight
		 */
		highlight: () => LocalizedString
		/**
		 * Image
		 */
		image: () => LocalizedString
		/**
		 * Remove color
		 */
		removeColor: () => LocalizedString
	}
	link: {
		/**
		 * New link
		 */
		newLink: () => LocalizedString
		/**
		 * URL
		 */
		url: () => LocalizedString
		/**
		 * Link title
		 */
		title: () => LocalizedString
		/**
		 * Copy link to clipboard
		 */
		copy: () => LocalizedString
		/**
		 * Open link in new tab
		 */
		open: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Remove link
		 */
		unlink: () => LocalizedString
	}
	image: {
		/**
		 * Full screen
		 */
		view: () => LocalizedString
		/**
		 * Delete
		 */
		remove: () => LocalizedString
		/**
		 * Previous
		 */
		previous: () => LocalizedString
		/**
		 * Next
		 */
		next: () => LocalizedString
		/**
		 * Close (Esc)
		 */
		close: () => LocalizedString
		/**
		 * The image cannot be loaded
		 */
		loadingError: () => LocalizedString
		/**
		 * Zoom out
		 */
		zoomOut: () => LocalizedString
		/**
		 * Zoom in
		 */
		zoomIn: () => LocalizedString
	}
}

export type Formatters = {}
