name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_on_chrome:
    name: Chrome Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Chrome
        run: pnpm install:chrome

      - name: Find problems
        run: pnpm lint

      - name: Run tests
        run: pnpm test
